### ISSUE TITLE
Проблема с вёрсткой

### ISSUE THREAD

**Issue by TheWitnessOfXeon** [SthephanShinkufag/atomboard#1]
Поставил самую новую версию на момент открытия issue,использовал режим flatfile, открыл imgboard.php, вёрстка едет, тема не работает(всё чёрно-белое и значки огромны), manage не работает. Что мне делать? Вот пример: hexochan.tk

**Comment by SthephanShinkufag** [comment]
You do it wrong.
Всё должно быть в папке `hexochan.tk/{имя борды}`
Судя по линкам в head, вы задали имя как `'b'`:
```php
define('TINYIB_BOARD', 'b');
```
Значит, всё должно лежать в папке `hexochan.tk/b`.
Я не предусматривал размещение борды в корневом каталоге домена.

**Comment by TheWitnessOfXeon** [comment]
Oh shit I'm sorry. Спасибо огромное.

**Comment by SthephanShinkufag** [comment]
Спрашивайте, ежели что. Самому интересно, с чем будут сталкиваться люди в боевых условиях.
