### ISSUE TITLE
Back button works incorrectly 

### ISSUE THREAD

**Issue by desertkun** [SthephanShinkufag/atomboard#16]
Quote from someone:

> Так, я когда нажимаю Rerutn в верху треда, у меня не возвращается на доску, а срабатывает браузерная команда Назад (<-).

**Comment by SthephanShinkufag** [comment]
Специально так сделал.
Постоянно были жалобы от многих, что выбрасывало на доску. При ошибке капчи например. Человек пишет пост в треде, его бросает на доску, он отправляет заново и создаёт по ошибке новый тред.

**Comment by SthephanShinkufag** [comment]
Хм, если перемещаться по ссылкам с якорями, нельзя будет выйти из треда. Тут да, надо фиксить.

**Comment by SthephanShinkufag** [comment]
Fix: 9de262b2d8dff3ba9273eae5327295e7cb4070d7
