### ISSUE TITLE
Название раздела по-русски

### ISSUE THREAD

**Issue by TheWitnessOfXeon** [SthephanShinkufag/atomboard#2]
Окей босс, у нас новая проблема:
Название раздела на русском не отображаются, показывая ромбики:
http://imgur.com/gallery/AN380Fl
Также вопрос: зачем раздел test? Он же не работает. 
И ещё один: как возможно создание нескольких разделов?

**Comment by SthephanShinkufag** [comment]
Кнопка `Test` нужна для особо непонятливых, для примера, что в `TINYIB_HTML_LEFTSIDE` можно добавлять свои кнопки с ссылками. На какую-нибудь вашу страницу, например, или другую доску. Всё ведь настраивается, какие проблемы?
Захотели - добавили, захотели удалили.
Режим `TINYIB_DBMODE === 'flatfile'` создаёт файлы с данными прямо на сервере, вместо "настоящей" базы данных. Файлам необходима кодировка UTF8. Если у вас по-умолчаию для файлов другая кодировка, её необходимо настроить. Настройте свой сервер (или, к примеру, ISP-менеджер вашего хостинга) так, чтобы все новые файлы были с кодировкой UTF8.

**Comment by SthephanShinkufag** [comment]
Или, например, можете создать в корневой папке файл `.codepage` с вот таким содержимым:
```
UTF-8
```

**Comment by TheWitnessOfXeon** [comment]
Проблема была в текстовом редакторе, исправил, спасибо, можете закрывать оба issue. Опишите ещё, пожалуйста, как можно сделать несколько досок, или TinyIB не предусмотрена для этого?

**Comment by SthephanShinkufag** [comment]
Если что, файлы данных хранятся здесь:
```
/b/inc/flatfile/.posts
/b/inc/flatfile/.posts.lock
```
> как можно сделать несколько досок

Вы можете создать так несколько досок также, как и эту. Каждая со своими настройками в отдельной папке. Например, создаёте доску `hexochan.tk/a`, изменяете в ней кнопку /test на /b, например, а в /b изменяете /test на /a. Всё, у вас две доски, связанные между собой ссылками.

**Comment by TheWitnessOfXeon** [comment]
При использование базы данных, две доски будут использовать две базы данных, или они смогут делить одну на двоих?

**Comment by SthephanShinkufag** [comment]
У каждой доски своя база.
Этот движок - конструктор для вашей фантазии. Его сила в примитивности.
Если вы хотите комбайн со свистелками и перделками на миллион досок, где нужно ничего не делать, а всё было, тогда вы выбрали не тот движок.
Вам нужно смотреть в сторону Vichan, OpenIB, Meguca, Lynxchan, и т.д.
